ifndef::imagesdir[:imagesdir: ../images]
= Luna

== Étkezés
Reggelire séta után *45g száraztáp + 45g tasakos* a tetejére.

Vacsora negyed hét és hét között (ha később értek haza akkor sem fog éhen halni)
*45g száraztáp + 45g tasakos* a tetejére.

Száraztáp a konyha ajtó melletti széken zsákban, tasakos ha van bontott,
akkor a hűtőben, ha nincs akkor az ajtó mögötti polcon található.

== Séta

Hám helye: fürdőszoba földön

* Reggel felkelés után, 8 körül
* Munka után hazaérve
* Vacsi után (Ha úgy alakul egybe is eshet a hazaérkezőssel)
* Utána hozza a hámot, vagy beül a fürdőszoba ajtóba és néz
** Ha séta után egy órán belül megint hozza, akkor az hiszti
* Utolsó séta 10 körül szokott lenni, de csak egy pisi
* Sétáltatós zacsi az előszobában a kis asztalon
* Ha kakilt, akkor szokott fent kapni egy juti falit

== Játék

* labdázás max este 8-ig, utána legfeljebb kötél húzás
* Üres műanyag palackokat imádja, ha megtartanátok, akkor érdemes asztalra, polcra tenni, mert 2 pillanat alatt ellopja

== Állatorvos

Boxi-Vet

Név:: Szepesi Orsi
Telefon:: +36-20-515-1675
Cím:: Budapest, Medve u. 23, 1027

Kiskönyv a hálóban a bejárathoz közelebbi éjjeli szekrény felső fiókjában.


