ifndef::imagesdir[:imagesdir: ../images]
= Luna

== Étkezés
Reggelire séta után *75g száraztáp* + 1 fél sonka összetépve a tál alján + 1 db allergia gyógyszer.

Vacsora fél hat körül (ha később érsz haza akkor sem fog éhen halni)
*75g száraztáp* + 1 fél sonka összetépve a tál alján.

Száraztáp a konyha ajtó melletti széken zsákban található.

== Séta

* Reggel felkelés után
* Munka után hazaérve, ha ez egybe esik a vacsival, akkor előbb vacsi.
* Utolsó séta 8-10 között.
* Sétáltatós zacsi az előszobában a kis asztalon
* Ha kakilt, akkor szokott fent kapni 2 db juti falit a tápból

== Játék

* labdázás max este 7-ig, utána legfeljebb kötél húzás
* ha megunja a labdát, de még játszana, akkor a "dobálós"-t lehet kérni, hogy keresse meg
* Üres műanyag palackokat imádja, ha megtartanád, akkor érdemes asztalra, polcra tenni, mert 2 pillanat alatt ellopja

== Állatorvos

Boxi-Vet

Név:: Szepesi Orsi
Telefon:: +36-20-515-1675
Cím:: Budapest, Medve u. 23, 1027

Kiskönyv a hálóban a bejárathoz közelebbi éjjeli szekrényen.
