ifndef::imagesdir[:imagesdir: ../images]
= Luna

== Étkezés
Reggelire séta után *75g száraztáp*.

Vacsora hat és hét között (ha később érsz haza akkor sem fog éhen halni)
*75g száraztáp*.

Száraztáp a konyha ajtó melletti széken zsákban található.

== Séta

Hám helye: fürdőszoba földön

* Reggel felkelés után
* Munka után hazaérve, ha ez egybe esik a vacsival, akkor előbb vacsi.
* Vacsi után (Ha nem esett egybe a hazaérkezőssel)
* Utána hozza a hámot, vagy beül a fürdőszoba ajtóba és néz, ha kell menni, de ez nem mindig kell.
** Ha séta után egy/másfél órán belül megint hozza, akkor az hiszti
* Utolsó séta 10 körül szokott lenni, de csak egy pisi
* Sétáltatós zacsi az előszobában a kis asztalon
* Ha kakilt, akkor szokott fent kapni 3 db juti falit az üvegtálból a kisasztalon.

== Játék

* labdázás max este 7-ig, utána legfeljebb kötél húzás
* Üres műanyag palackokat imádja, ha megtartanád, akkor érdemes asztalra, polcra tenni, mert 2 pillanat alatt ellopja

== Állatorvos

Boxi-Vet

Név:: Szepesi Orsi
Telefon:: +36-20-515-1675
Cím:: Budapest, Medve u. 23, 1027

Kiskönyv a hálóban a bejárathoz közelebbi éjjeli szekrény felső fiókjában.


