# This workflow will generate html documentation from asciidoc and publish it to `gh-pages` branch
name: Deploy documentation
on:
  push:
    branches:
      - main

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch [main]
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Push [main] to [gh-pages]
        shell: bash
        run: git push origin main:gh-pages --force
      - name: Checkout [gh-pages]
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Generate docs with Maven
        run: |
          mvn org.asciidoctor:asciidoctor-maven-plugin:1.6.0:process-asciidoc \
          -Dasciidoctor.sourceDirectory=./docs \
          -Dasciidoctor.outputDirectory=. \
          -Dasciidoctor.preserveDirectories=true \
          -Dasciidoctor.sourceHighlighter=coderay \
          -Dasciidoctor.backend=html5
      - name: Commit and push to [gh-pages]
        shell: bash
        run: |
          git config --global user.email "am-home@github.com"
          git config --global user.name "Github Action - Deploy pages"
          git add .
          git commit -m "Add auto-generated documentation"
          git push origin gh-pages --force
